-- create_job.lua
--
-- Atomic job creation script for ProjectX contract.gateway.
--
-- Guarantees:
--   1) Idempotency key check/set and job creation happen atomically.
--   2) job hash write, queued event write, and queue enqueue happen atomically.
--
-- KEYS:
--   [1] idempotency key (or "" when idempotency disabled)
--   [2] job hash key        (e.g. "job:{id}")
--   [3] events stream key   (e.g. "job:{id}:events")
--   [4] queue stream key    (e.g. "jobs:stream")
--
-- ARGV:
--   [1] use_idem            ("1" | "0")
--   [2] ttl_s               (integer seconds; <=0 means no EXPIRE)
--   [3] job_id              (new job uuid generated by caller)
--   [4] task                (task string)
--   [5] payload_json        (serialized payload)
--   [6] created_ts          (epoch millis as string)
--   [7] queued_step         (event step, e.g. "gateway.enqueue")
--   [8] queued_data_json    (queued event data json)

local idem_key = KEYS[1]
local job_hash_key = KEYS[2]
local events_stream_key = KEYS[3]
local queue_stream_key = KEYS[4]

local use_idem = ARGV[1]
local ttl_s = tonumber(ARGV[2])
local job_id = ARGV[3]
local task = ARGV[4]
local payload_json = ARGV[5]
local created_ts = ARGV[6]
local queued_step = ARGV[7]
local queued_data_json = ARGV[8]

if use_idem == "1" then
  local existing_job_id = redis.call("GET", idem_key)
  if existing_job_id then
    return { existing_job_id, "1" }
  end
end

redis.call(
  "HSET",
  job_hash_key,
  "job_id", job_id,
  "task", task,
  "payload", payload_json,
  "status", "queued",
  "created_ts", created_ts,
  "updated_ts", created_ts,
  "ttl_s", tostring(ttl_s),
  "result", "",
  "error", ""
)

if ttl_s ~= nil and ttl_s > 0 then
  redis.call("EXPIRE", job_hash_key, ttl_s)
end

redis.call(
  "XADD",
  events_stream_key,
  "*",
  "type", "queued",
  "ts", created_ts,
  "step", queued_step,
  "data", queued_data_json
)

if ttl_s ~= nil and ttl_s > 0 then
  redis.call("EXPIRE", events_stream_key, ttl_s)
end

redis.call(
  "XADD",
  queue_stream_key,
  "*",
  "job_id", job_id,
  "task", task,
  "payload", payload_json
)

if use_idem == "1" then
  if ttl_s ~= nil and ttl_s > 0 then
    redis.call("SET", idem_key, job_id, "EX", ttl_s)
  else
    redis.call("SET", idem_key, job_id)
  end
end

return { job_id, "0" }
